bonafidesale/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy
from django.utils.functional import curry
from django.views.defaults import permission_denied, page_not_found, server_error, bad_request

from main.utils import global_search_view, shop_search_view, product_set_rating_view, favorite_product_add_remove_view, \
    permission_view, likely_product_add_remove_view
from main.views import main_view, about_view, delivery_view, return_view, catalog_view, police_view, user_confirm_view, \
    oferta_view, back_view
from order.views import cart_view, add_to_cart_view, remove_from_cart_view, remove_all_from_cart_view, \
    change_item_count_view, to_order_view, create_notification_view
from shop.views import product_view, product_add_comment_view
from shopadmin.views import shopadmin_view, category_remove_view, category_add_view, category_edit_view, \
    product_edit_view, product_remove_view, product_add_view, product_photo_remove_view, sale_remove_view, sale_add_view
from tester.views import tester_view
from user.utils import password_change_view, password_reset_handler_view, password_reset_change_view, login_view, \
    registration_view
from user.views import profile_view, anonymous_profile_view

handler400 = 'main.views.handler400'
handler403 = 'main.views.handler403'
handler404 = 'main.views.handler404'
handler500 = 'main.views.handler500'

urlpatterns = [

    url(r'^admin/', admin.site.urls),

    url(r'^$', main_view, name='main'),

    url(r'^catalog/$', catalog_view, name='catalog'),
    url(r'^catalog/(?P<category>[-\w]+)/$', catalog_view, name='catalog'),

    url(r'^about/$', about_view, name='about'),
    url(r'^return/$', return_view, name='return'),
    url(r'^delivery/$', delivery_view, name='delivery'),
    url(r'^police/$', police_view, name='police'),
    url(r'^user_confirm/$', user_confirm_view, name='user_confirm'),
    url(r'^oferta/$', oferta_view, name='oferta'),

    url(r'^back/$', back_view, name='back'),

    url(r'^global_search/$', global_search_view, name='global_search'),
    url(r'^shop_search/$', shop_search_view, name='shop_search'),

    url(r'^all/(?P<product_slug>[-\w]+)/$', product_view, name='product'),

    url(r'^cart/$', cart_view, name='cart'),

    url(r'^to_order/$', to_order_view, name='to_order'),

    url(r'^add_to_cart/$', add_to_cart_view, name='add_to_cart'),

    url(r'^change_item_count/$', change_item_count_view, name='change_item_count'),
    url(r'^remove_from_cart/$', remove_from_cart_view, name='remove_from_cart'),
    url(r'^remove_all_from_cart/$', remove_all_from_cart_view, name='remove_all_from_cart'),

    url(r'^create_notification/$', create_notification_view, name='create_notification'),

    url(r'^product_set_rating/$', product_set_rating_view, name='product_set_rating'),
    url(r'^product_add_comment/$', product_add_comment_view, name='product_add_comment'),
    url(r'^likely_product_add_remove/$', likely_product_add_remove_view, name='likely_product_add_remove'),

    url(r'^favorite_product_add_remove/$', favorite_product_add_remove_view, name='favorite_product_add_remove'),

    url(r'^profile/$', profile_view, name='profile'),

    url(r'^anonymous_profile/$', anonymous_profile_view, name='anonymous_profile'),

    url(r'^shopadmin/$', shopadmin_view, name='shopadmin'),

    url(r'^sale_remove/$', sale_remove_view, name='sale_remove'),
    url(r'^sale_add/$', sale_add_view, name='sale_add'),

    url(r'^category_edit/$', category_edit_view, name='category_edit'),
    url(r'^category_remove/$', category_remove_view, name='category_remove'),
    url(r'^category_add/$', category_add_view, name='category_add'),

    url(r'^product_edit/$', product_edit_view, name='product_edit'),
    url(r'^product_remove/$', product_remove_view, name='product_remove'),
    url(r'^product_add/$', product_add_view, name='product_add'),
    url(r'^product_photo_remove/$', product_photo_remove_view, name='product_photo_remove'),

    url(r'^tester/$', tester_view, name='tester'),

    url(r'^password_change/$', password_change_view, name='password_change'),
    url(r'^password_reset_change/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', password_reset_change_view.as_view(),
        name='password_reset_change'),
    url(r'^password_reset_handler/$', password_reset_handler_view, name='password_reset_handler'),
    url(r'^login/$', login_view, name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('main')), name='logout'),
    url(r'^registration/$', registration_view, name='registration'),

    url(r'^permission/$', permission_view, name='permission'),
    url(r'^', include('social_django.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
from django.db.models import Q
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.encoding import python_2_unicode_compatible

from shop.models import Product, ProductSize


@python_2_unicode_compatible
class Address(models.Model):
    name = models.CharField(max_length=120, verbose_name='Имя', null=True)
    surname = models.CharField(max_length=120, verbose_name='Фамилия', null=True)
    fathername = models.CharField(max_length=120, verbose_name='Отчество', null=True)
    phone = models.CharField(max_length=120, verbose_name='Телефон', null=True)
    email = models.EmailField(verbose_name='E-mail', null=True)
    country = models.CharField(max_length=120, verbose_name='Страна', default="Россия", null=True)
    region = models.CharField(max_length=120, verbose_name='Регион/Область', null=True)
    area = models.CharField(max_length=120, verbose_name='Район', null=True, blank=True)
    city = models.CharField(max_length=120, verbose_name='Город/Населенный пункт', null=True)
    street = models.CharField(max_length=120, verbose_name='Улица', null=True)
    house = models.CharField(max_length=120, verbose_name='Дом', null=True)
    room = models.CharField(max_length=120, verbose_name='Квартира', null=True, blank=True)
    index = models.CharField(max_length=120, verbose_name='Индекс', null=True)

    class Meta:
        abstract = True


ORDER_STATUS_CHOICES = (
    ('new', 'Новый, ожидается регистрация'),
    ('registered', 'Ожидается оплата'),
    ('ready_to_send', 'Готов к отправке'),
    ('sender', 'Отправлено'),
    ('finish', 'Завершен')
)


@python_2_unicode_compatible
class Order(Address):
    items = models.ManyToManyField('CartItem', blank=True, related_name='order', verbose_name="Товары в заказе")
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name='order',
                             verbose_name="Пользователь")
    status = models.CharField(max_length=100, choices=ORDER_STATUS_CHOICES, default=ORDER_STATUS_CHOICES[0][0],
                              verbose_name="Статус заказа")
    date = models.DateTimeField(auto_now_add=True, verbose_name="Дата добавления")
    sk = models.TextField(verbose_name="Корзина гостя", blank=True)
    pay = models.BooleanField(default=False, verbose_name="Оплачено")

    send_confirm = models.BooleanField(default=False, verbose_name="Подтверждена доставка")

    pr_batch_name = models.TextField(max_length=100, verbose_name="Имя отправления", blank=True)
    pr_id = models.TextField(max_length=100, verbose_name="Номер отправления", blank=True)
    pr_barcode = models.TextField(max_length=100, verbose_name="Трек-номер", blank=True)
    pr_doc = models.BooleanField(default=False, verbose_name="Отправлено в ОПС")

    price_all = models.DecimalField(max_digits=9, decimal_places=2, default=0.00, verbose_name="Стоимость товаров")
    delivery_price = models.DecimalField(max_digits=9, decimal_places=2, default=0.00,
                                         verbose_name="Стоимость доставки")
    delivery_cart_price = models.DecimalField(max_digits=9, decimal_places=2, default=0.00, verbose_name="Итого")

    promo = models.CharField(max_length=100, verbose_name='Промокод', blank=True)
    sale = models.PositiveIntegerField(default=0, verbose_name='Скидка', blank=True)

    def archive(self):
        for it in self.items.all():
            it.archive_product_url = it.product.get_absolute_url()
            it.archive_product_name = it.product.name
            it.archive_product_id = it.product.id
            it.archive_product_base_price = it.product.base_price
            it.archive_product_sale = it.product.sale
            it.archive_product_price = it.product.price
            it.archive_size = it.size.size
            it.archive_count = it.count
            it.archive_price_all = it.price_all
            it.save()

    def group_name(self):
        return "user" + str(self.user.id) + "andshop_bonafidesale"

    def order_from_cart(self, cart):
        self.items.set(cart.items.all())
        self.user = cart.user
        self.CalculatePrice()

    def incr_buy_for_items(self):
        for item in self.items.all():
            item.product.incr_buy()

    def CalculatePrice(self):
        self.price_all = 0
        for item in self.items.all():
            self.price_all += item.CalculatePrice()
        self.save()

    def __str__(self):
        return str(self.id)


@python_2_unicode_compatible
class Cart(models.Model):
    items = models.ManyToManyField('CartItem', blank=True, related_name='cart', verbose_name="Товары в корзине")
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True, verbose_name="Пользователь")
    price_all = models.DecimalField(max_digits=9, decimal_places=2, default=0.00, verbose_name="Итого")
    sk = models.TextField(verbose_name="Корзина гостя", blank=True)

    def cart_from_order(self, order):
        self.items.set(order.items.all())
        self.user = order.user
        self.CalculatePrice()

    def __str__(self):
        try:
            ret = str(self.id) + " " + self.user.username
        except:
            ret = 'Не зарегистрированный'
        return ret

    def CalculatePrice(self):
        self.price_all = 0
        for item in self.items.all():
            self.price_all += item.CalculatePrice()
        self.save()
        return self.price_all

    def add_to_cart(self, product_id, size_id):

        product = Product.objects.get(id=product_id)
        size = ProductSize.objects.get(id=size_id)

        try:
            current_cart_item = self.items.get(Q(product=product) & Q(size_id=size_id))
            if current_cart_item.size != size:
                raise NameError('Not Item')

            if current_cart_item.count < size.count:
                current_cart_item.count += 1
            current_cart_item.CalculatePrice()
        except:
            new_cart_item = CartItem()
            new_cart_item.product = product
            new_cart_item.size = size
            new_cart_item.count = 1
            new_cart_item.CalculatePrice()
            self.items.add(new_cart_item)
        self.CalculatePrice()

        return "success"

    def change_item_count(self, item_id, size_id, count, ):

        cart_item = self.items.get(Q(id=int(item_id)) & Q(size_id=int(size_id)))
        cart_item.count = count
        cart_item.CalculatePrice()
        cart_item.save()
        self.CalculatePrice()
        return cart_item

    def remove_from_cart(self, product_id, size_id):

        product = Product.objects.get(id=product_id)
        cart_item = self.items.get(Q(product=product) & Q(size_id=size_id))
        self.items.remove(cart_item)
        cart_item.delete()
        self.CalculatePrice()

    def remove_all_from_cart(self, delete=True):

        for item in self.items.all():
            self.items.remove(item)
            if delete == True:
                item.delete()
        self.CalculatePrice()
        self.save()


@receiver(post_save, sender=User)
def create_or_update_user_cart(sender, instance, created, **kwargs):
    try:
        if created:
            Cart.objects.create(user=instance)
        instance.cart.save()
    except:
        return


@python_2_unicode_compatible
class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Товар')
    size = models.ForeignKey(ProductSize, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Размер')
    count = models.PositiveIntegerField(default=0, verbose_name='Кол-во')
    price_all = models.DecimalField(max_digits=9, decimal_places=2, default=0.00, verbose_name='Сумма')
    archive_product_url = models.SlugField(blank=True, max_length=120)
    archive_product_name = models.CharField(max_length=120, verbose_name='архив_Наименование', blank=True)
    archive_product_id = models.PositiveIntegerField(default=0, verbose_name='архив_ID', blank=True)

    archive_product_base_price = models.DecimalField(max_digits=9, decimal_places=2, default=0,
                                                     verbose_name='архив_Цена',
                                                     blank=True)
    archive_product_sale = models.PositiveIntegerField(default=0, verbose_name='архив_Скидка', blank=True)
    archive_product_price = models.DecimalField(max_digits=9, decimal_places=2, default=0,
                                                verbose_name='архив_Сумма со скидкой', blank=True)

    archive_size = models.CharField(max_length=100, verbose_name='архив_Размер', blank=True)
    archive_count = models.PositiveIntegerField(default=0, verbose_name='архив_Кол-во', blank=True)
    archive_price_all = models.DecimalField(max_digits=9, decimal_places=2, default=0.00, verbose_name='архив_Сумма',
                                            blank=True)

    def CalculatePrice(self):
        self.price_all = self.product.price * int(self.count)
        self.save()
        return self.price_all

    def __str__(self):
        return "Элемент корзины для товара {0}".format(self.product.name)

user/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.encoding import python_2_unicode_compatible

from order.models import Address
from shop.models import Product


@python_2_unicode_compatible
class Profile(Address):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="Пользователь")
    social = models.BooleanField(default=False, verbose_name="Вход через соц.сеть")

    favorite_products = models.ManyToManyField(Product, related_name='favorite_products', blank=True,
                                              verbose_name="Избранные товары")

    rating_products = models.ManyToManyField(Product, related_name='rating_products', blank=True,
                                             verbose_name="Рейтинг товаров")

    likely_products = models.ManyToManyField(Product, related_name='likely_products', blank=True,
                                             verbose_name="Лайки товаров")


    def __str__(self):
        return "Профиль для " + self.user.username


@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    try:
        if created:
            Profile.objects.create(user=instance)
            instance.profile.social = instance.social_auth.exists()
            instance.profile.name = instance.first_name
            instance.profile.surname = instance.last_name
            instance.profile.email = instance.email
            instance.profile.save()
        return
    except:
        return

user/templates/address_change.html
{% load mptt_tags %}
{% load bootstrap4 %}
{#{% bootstrap_css %}#}
{% load static %}
<link href="{% static "css/suggestions.min.css" %}" rel="stylesheet"/>
<script src="https://cdn.jsdelivr.net/npm/suggestions-jquery@19.4.1/dist/js/jquery.suggestions.min.js"></script>

<script>

    $(document).ready(function () {

        function showPostalCode(suggestion) {
            $("#id_index").val(suggestion.data.postal_code);
        }

        function clearPostalCode() {
            $("#id_index").val("");
        }

        var
            token = "47d7d7e598f04af6db6ef1ad5f0b2460d8b1bc97",
            type = "ADDRESS",
            $region = $("#id_region"),
            $area = $("#id_area"),
            $city = $("#id_city"),
            $street = $("#id_street");

        // регион
        $region.suggestions({
            token: token,
            type: type,
            hint: false,
            mobileWidth: "10",
            bounds: "region",
        });

        // район
        $area.suggestions({
            token: token,
            type: type,
            hint: false,
            bounds: "area",
            mobileWidth: "10",
            constraints: $region
        });

        // город и населенный пункт
        $city.suggestions({
            token: token,
            type: type,
            hint: false,
            bounds: "city-settlement",
            mobileWidth: "10",
            constraints: $area,
            onSelect: showPostalCode,
            onSelectNothing: clearPostalCode
        });

        // улица
        $street.suggestions({
            token: token,
            type: type,
            hint: false,
            bounds: "street",
            mobileWidth: "10",
            constraints: $city
        });
    });
</script>


<form id="address_form">
    {% csrf_token %}

    <div class="form-row">
        <div class="col">
            {% bootstrap_field address_form.name required_css_class='not_message' show_help=False %}
        </div>
        <div class="col">
            {% bootstrap_field address_form.surname required_css_class='not_message' show_help=False %}
        </div>
    </div>

    {% bootstrap_field address_form.fathername required_css_class='not_message' show_help=False %}

    <div class="form-row">
        <div class="col">
            {% bootstrap_field address_form.phone required_css_class='not_message' show_help=False %}
        </div>
        <div class="col">
            {% bootstrap_field address_form.email required_css_class='not_message' show_help=False %}
        </div>
    </div>

    <div class="form-row">
        <div class="col">
            {% bootstrap_field address_form.country required_css_class='not_message' show_help=False %}
        </div>
        <div class="col">
            {% bootstrap_field address_form.region required_css_class='not_message' show_help=False %}
        </div>
    </div>

    <div class="form-row">
        <div class="col">
            {% bootstrap_field address_form.area required_css_class='not_message' show_help=False %}
        </div>
        <div class="col">
            {% bootstrap_field address_form.city required_css_class='not_message' show_help=False %}
        </div>
    </div>

    {% bootstrap_field address_form.street required_css_class='not_message' show_help=False %}

    <div class="form-row">
        <div class="col">
            {% bootstrap_field address_form.index required_css_class='not_message' show_help=False %}
        </div>
        <div class="col">
            {% bootstrap_field address_form.house required_css_class='not_message' show_help=False %}
        </div>
        <div class="col">
            {% bootstrap_field address_form.room required_css_class='not_message' show_help=False %}
        </div>
    </div>



    {% if with_save == "true" %}
        <button type="submit" class="mt-2 btn__custom__inverse">Сохранить</button>
    {% endif %}
</form>

user/templates/anonymous_profile.html
{% extends 'script.html' %}

{% block title %}Bona Fide Sale - Личный кабинет{% endblock title %}

{% block scr %}

    <script>

        $(document).ready(function () {


            $(document).on('click', '.order_confirm_delivery', function (e) {
                e.stopPropagation();
                order_id = $(this).attr('id');
                btn = $(this);

                data = {
                    order_id: order_id,
                    method: "order_confirm_delivery"
                };
                $.ajax({
                    type: "GET",
                    url: '{% url "anonymous_profile" %}',
                    data: data,
                    success: function (data) {

                        if (data['result'] == 'success') {
                            btn.replaceWith("                    <div class=' w-100 mt-3 d-flex order_desc_head justify-content-center' style='color: gray'>\n" +
                                "                        Доставка подтверждена\n" +
                                "                    </div>");
                        } else if (data['result'] == 'error') {

                        }
                    }
                });
            });

            $(document).on('click', '.order_track', function (e) {
                e.stopPropagation();
                hr = $(this).attr('hr');
                window.open(hr, '_blank ');
            });

            $(document).on('click', '.order', function (e) {
                e.preventDefault();
                order_id = $(this).attr('id');

                data = {
                    order_id: order_id,
                    method: "get_order"
                };
                $.ajax({
                    type: "GET",
                    url: '{% url "anonymous_profile" %}',
                    data: data,
                    success: function (data) {

                        if (data['result'] == 'success') {

                            $('#modal_order_desc .modal-body').empty();
                            $('#modal_order_desc .modal-body').append(data['order_response']);
                            $('#modal_order_desc').modal('show');
                        } else if (data['result'] == 'error') {

                        }
                    }
                });
            });

            var sp = '{{ success_pay}}';

            if (sp == 'True') {
                var ru = '{{ redirect_url }}';
                window.location.href = ru;
            }

            var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
            var socket_url = ws_scheme + '://' + window.location.host + "/ws/order_socket/";

            console.log(socket_url)

            var socket = new WebSocket(socket_url)

            socket.onmessage = function (event) {
                console.log('cart onmessage: ', event)
                var data = JSON.parse(event.data);
                var mes = data['message']

                var command = mes['command']

                if (command == "alarm") {
                    var item_event = mes['event']
                    var order_id = mes['order_id']

                    if (item_event == "new_item") {
                        $('#insert').append(mes['order_model'])
                    } else if (item_event == "select_status_change") {
                        $('#container_' + order_id).replaceWith(mes['order_model'])

                    }
                }


                sound_alarm()

            };


            socket.onopen = function (event) {
                console.log('cart onopen: ', event)
                user_id = $('#aboutz').attr("user_id");
                socket.send(JSON.stringify({
                    "command": "join",
                    "user_id": user_id
                }));
            };

            socket.onclose = function (event) {
                console.log('cart closed: ', event)
            };

        })
    </script>

{% endblock scr %}


{% block sidebar_button %}
    <button type="button" id="sidebarCollapse" class="mc btn__custom">
        <i class="fas fa-align-left"></i>
        <span>Меню</span>
    </button>
{% endblock sidebar_button %}


{% block content %}
    <section>
        <div class="anon__profile__section container-fluid">
            <div class="row">
                {% include 'sidebar.html' with class_m="mc" ovr='mc' filter_shop_display='none' %}

                <div class="row px-0 px-lg-3 col-12 mx-0 d-flex justify-content-center">
                    <div class="content col-12 px-0">
                        <div class="section__header">Ваши заказы</div>

                        <div id="insert"
                             class="col-12 px-0 row order_container d-flex justify-content-center">

                            {% if orders.count == 0 %}
                                {% include 'not_find.html' %}
                            {% else %}
                                {% for order in orders %}
                                    {% include 'object.html' %}
                                {% endfor %}
                            {% endif %}

                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>

    <div class="modal fade" id="modal_order_desc" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered" style="max-width: 95%;min-width: 70%">
            <div class="modal-content">

                <div class="modal-body order_container">

                </div>

                <div class="modal-footer">
                    <button type="button" class="btn__custom__inverse" data-dismiss="modal">Закрыть</button>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

user/templates/user_change.html
{% load mptt_tags %}
{% load bootstrap4 %}
{#{% bootstrap_css %}#}

<form id="user_form">
    {% csrf_token %}
    {% bootstrap_form user_form required_css_class='not_message' show_help=False %}
    <button type="submit" class="btn__custom">Сохранить</button>
</form>